name: Docker Deploy (Windows)

on:
  push:
    branches:
      - joseortega

jobs:
  build-and-run:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Build JAR con Maven
        run: mvn clean package

      - name: Construir imagen Docker
        run: docker build -t laboratorio-final-devops:1.0 .

      - name: Ejecutar contenedor
        run: docker run -d -p 8081:8081 --name laboratorio-final-devops laboratorio-final-devops:1.0

      - name: Verificar contenedores
        run: docker ps -a