name: Docker Deploy (Windows)

on:
  push:
    branches:
      - joseortega   # tu rama personalizada

jobs:
  build-and-run:
    runs-on: self-hosted   # tu runner local en Windows
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Limpiar contenedor previo si existe
        run: |
          docker stop laboratorio-final-devops 2>$null
          if ($LASTEXITCODE -ne 0) { echo "No estaba corriendo" }

          docker rm laboratorio-final-devops 2>$null
          if ($LASTEXITCODE -ne 0) { echo "No existía" }
        shell: pwsh

      - name: Construir imagen
        run: docker build -t laboratorio-final-devops:1.0 .
        shell: pwsh

      - name: Ejecutar contenedor
        run: docker run -d -p 8081:8081 --name laboratorio-final-devops laboratorio-final-devops:1.0
        shell: pwsh

      - name: Verificar contenedores activos
        run: docker ps -a
        shell: pwsh
